export default {
  ARTICLE_STORAGE: 'ARTICLE_STORAGE',
  GLOBAL_SETTINGS: 'GLOBAL_SETTINGS',
  FONT_SIZE: 'FONT_SIZE',
  SITES: 'SITES',
  NOTIFICATION_DATE: 'NOTIFICATION_DATE',
  FONT_SIZE_VALUE: 17,
  ACTIVE_SITE: 'behance'
};
